#!/usr/bin/env python3
"""Generate a deterministic architecture map from the active Python package."""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "src"
OUTPUT_PATH = ROOT / "docs" / "architecture.md"


@dataclass(frozen=True)
class ModuleInfo:
    name: str
    path: str
    dependencies: tuple[str, ...]
    public_symbols: tuple[str, ...]


def _module_name(path: Path) -> str:
    return path.stem if path.name != "__init__.py" else "package_init"


def _internal_dependencies(tree: ast.AST, module_names: set[str]) -> tuple[str, ...]:
    dependencies: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom) or node.level == 0:
            continue
        if node.module:
            candidate = node.module.split(".", 1)[0]
            if candidate in module_names:
                dependencies.add(candidate)
        else:
            dependencies.update(alias.name for alias in node.names if alias.name in module_names)
    return tuple(sorted(dependencies))


def scan_modules(source_dir: Path = SOURCE_DIR) -> list[ModuleInfo]:
    paths = sorted(source_dir.glob("*.py"))
    module_names = {_module_name(path) for path in paths}
    modules: list[ModuleInfo] = []
    for path in paths:
        tree = ast.parse(path.read_text(encoding="utf-8"), filename=str(path))
        public_symbols = sorted(
            node.name
            for node in tree.body
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_")
        )
        modules.append(
            ModuleInfo(
                name=_module_name(path),
                path=path.relative_to(ROOT).as_posix(),
                dependencies=_internal_dependencies(tree, module_names),
                public_symbols=tuple(public_symbols),
            )
        )
    return modules


def _mermaid_id(name: str) -> str:
    return "m_" + "".join(character if character.isalnum() else "_" for character in name)


def render_architecture(modules: list[ModuleInfo]) -> str:
    lines = [
        "# Architecture map",
        "",
        "> Generated by `python tools/generate_architecture.py`. Do not edit this file manually.",
        "",
        "This map covers the active Python package in `src/`. Historical reference bundles are intentionally excluded.",
        "",
        "## Pipeline flow",
        "",
        "```mermaid",
        "flowchart TD",
        '    config["LM Studio configuration"] --> extract["1. Extract chapter references"]',
        '    extract --> consolidate["2. Consolidate references"]',
        '    consolidate --> designs["Prepare visual designs"]',
        '    designs --> generate["3. Generate H3 prompts"]',
        '    consolidate --> generate',
        "```",
        "",
        "The node wrappers coordinate filesystem access, configuration snapshots and run outputs. The three `pipeline_step*` modules contain the LLM-facing stage implementations.",
        "",
        "## Internal module dependencies",
        "",
        "```mermaid",
        "flowchart TD",
    ]
    for module in modules:
        lines.append(f'    {_mermaid_id(module.name)}["{module.name}"]')
    for module in modules:
        for dependency in module.dependencies:
            lines.append(f"    {_mermaid_id(module.name)} --> {_mermaid_id(dependency)}")
    lines.extend(["```", "", "## Module inventory", "", "| Module | Internal dependencies | Public classes/functions |", "|---|---|---|"])
    for module in modules:
        dependencies = ", ".join(f"`{name}`" for name in module.dependencies) or "—"
        symbols = ", ".join(f"`{name}`" for name in module.public_symbols) or "—"
        lines.append(f"| `{module.path}` | {dependencies} | {symbols} |")
    lines.extend(["", f"Modules: **{len(modules)}**. Internal dependency edges: **{sum(len(module.dependencies) for module in modules)}**.", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed architecture map is stale.")
    args = parser.parse_args()
    rendered = render_architecture(scan_modules())
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
            parser.error("docs/architecture.md is stale; run python tools/generate_architecture.py")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
