#!/usr/bin/env python3
"""Generate a deterministic architecture map from the active Python package."""

from __future__ import annotations

import argparse
import ast
from dataclasses import dataclass
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "src"
OUTPUT_PATH = ROOT / "docs" / "architecture.md"


@dataclass(frozen=True)
class ModuleInfo:
    name: str
    path: str
    dependencies: tuple[str, ...]
    public_symbols: tuple[str, ...]
    comfyui_nodes: tuple[tuple[str, str], ...] = ()


def _module_name(path: Path) -> str:
    return path.stem if path.name != "__init__.py" else "package_init"


def _internal_dependencies(tree: ast.AST, module_names: set[str]) -> tuple[str, ...]:
    dependencies: set[str] = set()
    for node in ast.walk(tree):
        if not isinstance(node, ast.ImportFrom) or node.level == 0:
            continue
        if node.module:
            candidate = node.module.split(".", 1)[0]
            if candidate in module_names:
                dependencies.add(candidate)
        else:
            dependencies.update(alias.name for alias in node.names if alias.name in module_names)
    return tuple(sorted(dependencies))


def _registration_entries(tree: ast.AST, name: str) -> dict[str, ast.expr]:
    """Read literal registration dictionaries without importing the plugin."""
    entries: dict[str, ast.expr] = {}
    for node in ast.walk(tree):
        value = None
        if isinstance(node, (ast.Assign, ast.AnnAssign)):
            targets = node.targets if isinstance(node, ast.Assign) else [node.target]
            if any(isinstance(target, ast.Name) and target.id == name for target in targets):
                value = node.value
        elif (
            isinstance(node, ast.Call)
            and isinstance(node.func, ast.Attribute)
            and isinstance(node.func.value, ast.Name)
            and node.func.value.id == name
            and node.func.attr == "update"
            and len(node.args) == 1
        ):
            value = node.args[0]
        if isinstance(value, ast.Dict):
            for key, item in zip(value.keys, value.values):
                if isinstance(key, ast.Constant) and isinstance(key.value, str):
                    entries[key.value] = item
    return entries


def _comfyui_display_names(tree: ast.AST) -> dict[str, str]:
    classes = _registration_entries(tree, "NODE_CLASS_MAPPINGS")
    labels = _registration_entries(tree, "NODE_DISPLAY_NAME_MAPPINGS")
    names: dict[str, str] = {}
    for node_id, value in classes.items():
        class_name = value.attr if isinstance(value, ast.Attribute) else value.id if isinstance(value, ast.Name) else None
        label = labels.get(node_id)
        if class_name:
            names[class_name] = label.value if isinstance(label, ast.Constant) and isinstance(label.value, str) else node_id
    return names


def scan_modules(source_dir: Path = SOURCE_DIR) -> list[ModuleInfo]:
    paths = sorted(source_dir.glob("*.py"))
    module_names = {_module_name(path) for path in paths}
    trees = {path: ast.parse(path.read_text(encoding="utf-8"), filename=str(path)) for path in paths}
    display_names = _comfyui_display_names(trees[source_dir / "__init__.py"]) if source_dir / "__init__.py" in trees else {}
    modules: list[ModuleInfo] = []
    for path in paths:
        tree = trees[path]
        public_symbols = sorted(
            node.name
            for node in tree.body
            if isinstance(node, (ast.ClassDef, ast.FunctionDef, ast.AsyncFunctionDef)) and not node.name.startswith("_")
        )
        modules.append(
            ModuleInfo(
                name=_module_name(path),
                path=path.relative_to(ROOT).as_posix(),
                dependencies=_internal_dependencies(tree, module_names),
                public_symbols=tuple(public_symbols),
                comfyui_nodes=tuple(
                    (node.name, display_names[node.name])
                    for node in tree.body
                    if isinstance(node, ast.ClassDef) and node.name in display_names
                ),
            )
        )
    return modules


def _mermaid_id(name: str) -> str:
    return "m_" + "".join(character if character.isalnum() else "_" for character in name)


def _mermaid_label(label: str) -> str:
    return label.replace("&", "#38;").replace('"', "#quot;").replace("<", "#60;").replace(">", "#62;").replace("\n", "<br/>")


def render_architecture(modules: list[ModuleInfo]) -> str:
    display_names = dict(node for module in modules for node in module.comfyui_nodes)

    def node_label(class_name: str, fallback: str) -> str:
        return _mermaid_label(display_names.get(class_name, fallback))

    lines = [
        "# Architecture map",
        "",
        "> Generated by `python tools/generate_architecture.py`. Do not edit this file manually.",
        "",
        "This map covers the active Python package in `src/`.",
        "",
        "## Pipeline flow",
        "",
        "```mermaid",
        "flowchart TD",
        f'    selector["{node_label("SelectChaptersNode", "Select Chapters")}"] --> '
        f'adapter["{node_label("CinematicChapterAdapterNode", "Cinematic Chapter Adapter")}"]',
        '    config --> adapter',
        '    adapter --> adapted["Per-chapter sequence/source/adaptation JSON"]',
        '    adapted --> extract',
        f'    adapted --> loader["{node_label("LoadCinematicChaptersNode", "Load Cinematic Chapters")}"]',
        '    loader --> extract',
        f'    config["{node_label("LMStudioConfigurationNode", "LM Studio Configuration")}"] --> '
        f'extract["{node_label("ExtractChapterReferencesNode", "Extract Chapter References")}"]',
        f'    extract --> consolidate["{node_label("ConsolidateReferencesNode", "Consolidate References")}"]',
        '    consolidate --> timeline["Canonical entity timelines: chapter / sequence / phase"]',
        '    consolidate --> links["Editable reference links + JSON schemas; optional review-only pass"]',
        '    links --> decisions["Validate and apply confirmed identities, attributions and relations"]',
        '    decisions --> timeline',
        '    consolidate --> designs["Prepare stable visual designs"]',
        f'    designs --> generate["{node_label("GenerateH3PromptsNode", "Generate H3 Prompts")}"]',
        '    consolidate --> generate',
        '    selector --> generate',
        '    config --> generate',
        '    generate --> review["H3 validation, camera processing, temporal review/repair"]',
        "```",
        "",
        "The node wrappers coordinate filesystem access, configuration snapshots and run outputs. The three `pipeline_step*` modules contain the LLM-facing stage implementations.",
        "The standalone cinematic adapter uses `cinematic_adaptation` and the shared LM Studio JSON transport. Its ordered phases feed extraction; catalogs and registries retain temporal observations.",
        "",
        "`reference_timeline` validates cinematic catalogs, merges observations without rewriting them, computes first occurrences and provides exact-address state lookup. Identity reconciliation and duplicate audits exclude temporal state; base image briefs use stable identity only.",
        "`reference_links` reviews chapter evidence, validates editable source-addressed decisions and applies protected identities and scoped attributions before assets. Manifestations retain their original events without character assets. `editable_schemas` loads bundled `src/schema/*.json` files for import validation and copies them unchanged to run outputs; editor schema URLs are never fetched at runtime.",
        "",
        "## Internal module dependencies",
        "",
        "Only modules with incoming or outgoing internal dependency edges are shown. Labels include registered ComfyUI node names.",
        "",
        "```mermaid",
        "flowchart TD",
    ]
    connected = {module.name for module in modules if module.dependencies}
    connected.update(dependency for module in modules for dependency in module.dependencies)
    for module in modules:
        if module.name in connected:
            label = "<br/>".join(_mermaid_label(name) for name in [module.name, *(label for _, label in module.comfyui_nodes)])
            lines.append(f'    {_mermaid_id(module.name)}["{label}"]')
    for module in modules:
        for dependency in module.dependencies:
            lines.append(f"    {_mermaid_id(module.name)} --> {_mermaid_id(dependency)}")
    lines.extend(["```", "", "## Module inventory", "", "| Module | Internal dependencies | Public classes/functions |", "|---|---|---|"])
    for module in modules:
        dependencies = ", ".join(f"`{name}`" for name in module.dependencies) or "—"
        symbols = ", ".join(f"`{name}`" for name in module.public_symbols) or "—"
        lines.append(f"| `{module.path}` | {dependencies} | {symbols} |")
    lines.extend(["", f"Modules: **{len(modules)}**. Internal dependency edges: **{sum(len(module.dependencies) for module in modules)}**.", ""])
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Fail if the committed architecture map is stale.")
    args = parser.parse_args()
    rendered = render_architecture(scan_modules())
    if args.check:
        if not OUTPUT_PATH.exists() or OUTPUT_PATH.read_text(encoding="utf-8") != rendered:
            parser.error("docs/architecture.md is stale; run python tools/generate_architecture.py")
        return 0
    OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"Wrote {OUTPUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
